version: '2'
services:

  frontend:
    build: ./frontend
    container_name: yourappname_frontend
    command: npm run start
    ports:
      - '8080:80'
    volumes:
     - ./frontend:/app
    environment:
      NODE_ENV: development

  backend:
    build: ./backend
    container_name: yourappname_backend
    command: rails s -b 0.0.0.0 -p 3050
    ports:
      - '3050:3050'
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - bundle:/usr/local/bundle
      - db_data:/var/lib/postgresql/data
    environment:
      RAILS_ENV: development

  db:
    image: postgres:9.6
    container_name: yourappname_db
    ports:
      - '5432'

volumes:
  db_data:
  bundle:
