defaultEntryPoints = ["http", "https"]

[web]
address = ":8080"
  [web.auth.basic]
  users = ["admin:$apr1$U60jaJVg$9gYj7vjSs6Sg8eq...9vB/"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "bjrnsommer1990@yahoo.de"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = false

